### ISSUE TITLE
Why is my output video had red-filtered?

### ISSUE THREAD

**Issue by YukihimeX** [kijai/ComfyUI-WanVideoWrapper#60]
Any suggesting on how to get the output same as the input image?
Increase the steps from 10 to 20 doesn't seem to do the trick. Less flickering and more smooth but the color still had that red filtered feel to it. I'm using the i2v 480p workflow on this repo, and I haven't change anything other setting beside the width and height.

EDIT: Sorry, I mistook bf16 and fp16 bc I wasn't careful enough when I was reselect the models from my local drive (must have switch them by mistake). SO yes, that red filtered is because of the mismatch between model and precision. 

![Image](https://media.tenor.com/Wl5m0OTnM24AAAAM/oshi-no-ko-oshi-no-ko-ruby.gif) ![Image](https://i.pinimg.com/originals/8f/76/f0/8f76f034ccc458bd09675c0380f59cb7.gif)
![Image](https://github.com/user-attachments/assets/6acf0057-e249-4ef0-8249-6c5313f3e76f)

**Comment by kijai** [comment]
Hmmm haven't seen that for a while, at the start there was issue with the very first model I uploaded, but only for like couple of hours until I fixed it, it was more drastic color shift than that though. Is it consistently same with other images/seeds?

**Comment by YukihimeX** [comment]
> Hmmm haven't seen that for a while, at the start there was issue with the very first model I uploaded, but only for like couple of hours until I fixed it, it was more drastic color shift than that though. Is it consistently same with other images/seeds?

Yes I set seed to random and test a few other picture but still the same. Below have my exact setup. 

Here's my setup json.

[Wan21_kijai_480_10stp.json](https://github.com/user-attachments/files/19018082/Wan21_kijai_480_10stp.json)

**Comment by papandadj** [comment]
希望github出个NSFW标识,正常班呢,点开个这个
